alias vi=vim
alias ssh1='ssh -i .ssh/key.pem -p 2552 gbp-bst-01'
alias ssh2='ssh -i .ssh/key.pem -p 2552 gbp-bst-02'
alias ans='source ~/ansible/hacking/env-setup'

export HISTTIMEFORMAT='%d/%m/%y %T '
PS1='\n\033[0m\033[0;33m\]\u\033[0;33m\]@\h:\033[0m\]\w\033[0m\]\n\n$ '


